const BROAD_LABELS = [
  "window",
  "door",
  "sliding glass door",
  "garage door",
  "gate",
  "curtain",
  "blinds",
  "mirror",
  "wall",
  "floor",
  "ceiling",
  "stairs",
  "fence",
  "chair",
  "sofa",
  "table",
  "desk",
  "bed",
  "cabinet",
  "shelf",
  "television",
  "laptop",
  "computer monitor",
  "smartphone",
  "keyboard",
  "remote control",
  "refrigerator",
  "microwave",
  "oven",
  "stove",
  "sink",
  "toilet",
  "bathtub",
  "shower",
  "washing machine",
  "lamp",
  "picture frame",
  "clock",
  "plant",
  "tree",
  "person",
  "cat",
  "dog",
  "car",
  "bicycle",
  "book",
  "bottle",
  "cup",
  "backpack",
  "handbag",
  "shoes",
  "jacket",
  "cardboard box",
  "pillow",
  "rug",
  "vase",
];

const REFINE = {
  window: [
    "window",
    "bay window",
    "skylight",
    "shop window",
    "window with curtains",
    "window with blinds",
  ],
  door: [
    "wooden door",
    "front door",
    "interior door",
    "glass door",
    "sliding glass door",
    "screen door",
    "doorway",
  ],
  "sliding glass door": ["sliding glass door", "patio door", "glass door"],
  "garage door": ["garage door", "roll-up door"],
  chair: ["chair", "office chair", "dining chair", "armchair"],
  sofa: ["sofa", "couch", "loveseat"],
  table: ["table", "dining table", "coffee table"],
  television: ["television", "flat screen tv", "computer monitor"],
  smartphone: ["smartphone", "mobile phone"],
  plant: ["houseplant", "potted plant", "tree"],
  car: ["car", "sedan", "suv"],
  bottle: ["bottle", "water bottle", "wine bottle"],
};

const GENERIC_LABELS = new Set(["wall", "floor", "ceiling", "person"]);

export { BROAD_LABELS, REFINE, GENERIC_LABELS };
